### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by gordonzzl** [tjuyy/NanoPi-R1S-H5-Openwrt-Autobuild#8]
System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
Unhandled exception. System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)

**Comment by ZenWayne** [comment]
第一句，No space left on device，先卸载掉ubuntu容器的软件再操作吧，可以参考我的[yml更改](https://github.com/i6o6i/NanoPi-R1S-H5-Openwrt-Autobuild/commit/00903867a6f1b6d16b4819fa9caea6616d6c6088)

**Comment by ZenWayne** [comment]
看到你fork了，现在我的fork由于编译过程中目录名太长会出现以下错误

/home/runner/work/NanoPi-R1S-H5-Openwrt-Autobuild/NanoPi-R1S-H5-Openwrt-Autobuild/friendlywrt-h5/friendlywrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.3.0_musl/lib/gcc/aarch64-openwrt-linux-musl/8.3.0/../../../../aarch64-openwrt-linux-musl/bin/ar: array_type_info.o: No such file or directory
2020-04-12T08:17:50.7625348Z make[4]: *** [src/libuClibc++.a] Error 1
2020-04-12T08:17:50.7625816Z src/Makefile.in:44: recipe for target 'src/libuClibc++.a' failed
2020-04-12T08:17:50.7626679Z make[3]: *** [/home/runner/work/NanoPi-R1S-H5-Openwrt-Autobuild/NanoPi-R1S-H5-Openwrt-Autobuild/friendlywrt-h5/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/uClibc++-0.2.5/.built] Error 2
2020-04-12T08:17:50.7629016Z make[4]: Leaving directory '/home/runner/work/NanoPi-R1S-H5-Openwrt-Autobuild/NanoPi-R1S-H5-Openwrt-Autobuild/friendlywrt-h5/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/uClibc++-0.2.5'
2020-04-12T08:17:50.7629781Z Makefile:97: recipe for target '/home/runner/work/NanoPi-R1S-H5-Openwrt-Autobuild/NanoPi-R1S-H5-Openwrt-Autobuild/friendlywrt-h5/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/uClibc++-0.2.5/.built' failed
2020-04-12T08:17:50.7630427Z make[3]: Leaving directory 

所以我创了新的项目[NanoR1s](https://github.com/i6o6i/NanoR1s)
